server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: mybatisgx-example
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuyue_upms?characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password:

mybatisgx:
  mapper-locations: classpath:com/wuyue/upms/dao/mapper/*Mapper.xml
  type-aliases-package: com.wuyuw.upms.model.entity
  configuration:
    map-underscore-to-camel-case: true
    # lazy-loading-enabled: true