server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: mybatisgx-example
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisgx_example?characterEncoding=utf8&useUnicode=true&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456

mybatisgx:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mybatisgx.example.spring.boot.entity
  configuration:
    databaseId: MySQL
    # 懒加载配置
    lazy-loading-enabled: true
    aggressiveLazyLoading: false
    lazyLoadTriggerMethods: get
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.mybatisgx.template: DEBUG